### ISSUE TITLE
url-unshort does not work for tinyURL

### ISSUE THREAD

**Issue by alexcapitan** [nodeca/url-unshort#13]
Hi,

Just a small note on **tinyUrl** shortening service (https://github.com/nodeca/url-unshort/blob/master/domains.yml).

When shorten an URL with tinyUrl the process is:
1. Shorten the URL with tinyUrl.com
2. Access the shorten URL from step 1 will open the page **preview.tinyUrl.com**
3. Is a redirection but to an intermediary page that says:

_This TinyURL redirects to:
URL from step 1
Proceed to this site._

**Conclusion**:

url-unshort will receive the redirection code and interpret it as the full unshorten URL. So, in the end, for tinyUrl, url-unshorten will return preview.tinyURL and not the correct one.

**Comment by puzrin** [comment]
Do you have a reproducible case of real package use (not manual site use via browser)?

https://github.com/nodeca/url-unshort/blob/master/test/services.yml#L30 - that site has test, working as expected. But i could miss something.

If you insist on error in this package, i'd like to get minimal reproducible code sample prior to investigate.

**Comment by puzrin** [comment]
Could not reproduce. Please provide more info to reopen.
