### ISSUE TITLE
Hangs forever

### ISSUE THREAD

**Issue by mifi** [nodeca/url-unshort#9]
When used on something that is not a shortened url, it will hang forever:

```js
require('url-unshort')().expand('https://google.com/').then(console.log)
```

```
Promise { <pending> }
```

The promise will never resolve. IMO this is risky behavior and causes memory leaks on our server. I would expect it to for example throw an error

**Comment by rlidwka** [comment]
Sorry, I can't reproduce the error you have:

```sh
$ yarn add url-unshort
$ node -e "require('url-unshort')().expand('https://google.com/').then(x=>{console.log('resolves, result: ' + x)})"
resolves, result: null
```

It resolves perfectly fine, result is `null` as per documentation in README. My only guess is that your code works incorrectly with output in this case.

If you think it's a bug here, please send more details.

**Comment by mifi** [comment]
Now it's returning `null` for me as well. I'm not sure what changed since last time.

**Comment by puzrin** [comment]
This could be real network connection hang. Let's close until more info available. I believe you had problem, but still not sure it's in this package. Feel free to create new issue anytime.

**Comment by mifi** [comment]
Yes, although I want to say (for future reference) that it happened both on my laptop and on a production server running in AWS, over many days. And it happened not only for google.com (that was just an example for reproducing the issue)

**Comment by puzrin** [comment]
@mifi second possibility - some "broken" dependency of this package was fixed. But i can not imagine wich one could cause such effect.

The only thing we could do - migrate `got` => `needle` for sure, as we did in `probe-image-size`.

**Comment by mifi** [comment]
I was also thinking that something like that might have happened. Probably some dependency of url-unshort may have released a bad patch/minor version which was then in our lock files at that time but is now fixed. (I believe our service that was running in aws was recently deployed with url-unshort also)

**Comment by puzrin** [comment]
@mifi We are on the way to release new major version (see commits history).

- If you have reproducible samples of hangs - let me know.
- To be honest, in our app we wrap unshortener to `Promise.race` with timeout (pay with memory leaks for time guarantees).
- If you know good & battle-tested alternative to `got` - let me know. All packages i found have side effects (complexity, support, bugs).

**Comment by mifi** [comment]
Sounds good. I domt have any reproducable code other than the original snippet. I think got is very actively maintained and used in a lot of projects. Maybe axios is more battle tested but I think a bit more quirky because it supports both node and browser, while got is node only

**Comment by puzrin** [comment]
Example from first post does not pass domain's `.validate()`, it returns without network request. I have no ideas how it can hang.
